replicaCount: 1

image:
  repository: adminer
  tag: 4.8.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  class: nginx
  hosts:
    - default.nmaas.local
  tls:
    enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
